# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

sudo: none

dist: trusty

language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - gfortran-4.9
            - clang-3.7

install:
    ############################################################################
    # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
    ############################################################################
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

    ############################################################################
    # Install a recent CMake
    ############################################################################
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
        mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      else
        brew upgrade cmake || brew install cmake
      fi
    - cmake --version
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          export FC="gfortran-4.9";
          if [[ "$CXX" == "g++" ]]; then
              export CXX="g++-4.9";
              export CC="gcc-4.9";
          fi;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          travis_wait brew install gcc && brew install libidn && export FC="gfortran";
          brew install ccache;
          export PATH="/usr/local/opt/ccache/libexec:$PATH";
          brew install coreutils;
          export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH";
          rvm get stable --auto-dot-files;
          rvm reset;
      fi
    - echo ${PATH}
    - echo ${CC}
    - echo ${CXX}
    - echo ${FC}
    - curl --version
    - ${CC} --version
    - ${CXX} --version
    - ${FC} --version

before_script: |
  function keep_alive() {
    while true; do
      echo -en "\a"
      sleep 5
    done
  }
  keep_alive &


script:
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build
    #the configure needs this line suppression strategy
    - stdbuf -oL cmake .. 2>stderr.log |  grep --line-buffered '\[BootsOnTheGround\]\|\[hunter\]\|%\]'
    - cmake --build .
    - ctest

cache: ccache

